# Register image plugin for ckeditor
editor:
  externalPlugins:
    typo3image: { resource: "EXT:cnslider/Resources/Public/JavaScript/Plugins/typo3image.js", route: "rteckeditorimage_wizard_select_image" }
